baseURL = "https://gohugo.io/"
title = "StarWays"
author = "Steve Francia"
copyright = "Copyright (c) 2021 Jouad El Ouardi & Arturo Garrido"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
authorAvatar = "static/images/profile_image.jpeg"
theme = "casper3"
disableHugoGeneratorInject = "true"

[params]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  github = "https://github.com/Jouad01/Proyecto_Pydevops"
  description = "Encuentre la nave que necesita, y desagase de la que ya no necesite"
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "image-credit"
    name = "Agregue su Nave"
    url = "/vender/"
    weight = 20
  [[menu.main]]
    identifier = "naves_baratas"
    name = "Gama baja"
    url = "/tags/gama-baja/"
    weight = 30
  [[menu.main]]
    identifier = "naves_asequibles"
    name = "Gama media"
    url = "/tags/gama-media/"
    weight = 40
  [[menu.main]]
    identifier = "naves_de_lujo"
    name = "Gama alta"
    url = "/tags/gama-alta/"
    weight = 50


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.goldmark.renderer]
  unsafe = true